name: Build and deploy Node.js app to Azure Web App - BackendAppSMCN

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm ci  # Usa npm ci en lugar de npm install para builds

      - name: Create deployment package
        run: |
          # Crear directorio de producción
          mkdir deployment
          # Copiar archivos necesarios
          cp package*.json deployment/
          cp server.js deployment/
          cp -r config deployment/
          cp -r controller deployment/
          cp -r interface deployment/
          cp -r middleware deployment/
          cp -r models deployment/
          cp -r routes deployment/
          cp -r services deployment/
          cp .env deployment/ || true  # Copiar .env si existe
          cp initFirestore.js deployment/
          
          # Instalar dependencias de producción
          cd deployment
          npm ci --only=production
          cd ..
          
          # Crear ZIP desde el directorio de deployment
          cd deployment && zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          mkdir app
          unzip release.zip -d app
          cd app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88B6EFFAD46744FB9C3EEFDFC2231017 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02A9FA1B285149CBB2D0131EA7C9511A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BF4C133BE4742E091AAFF6C03C8F1A8 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BackendAppSMCN'
          slot-name: 'Production'
          package: app  # Actualizado para usar el directorio app